### ISSUE TITLE
SuiteSparse: enable vc-14-2015-win64

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1057]
I have a Problem with my Windows and linux tests

https://github.com/NeroBurner/hunter/commits/test.suitesparse

I based the branch `test.suitesparse` on `pkg.suitesparse`. Then I merged `pkg.template` (and fixed some merge conflicts). As last step I added the toolchain `vc-14-2015-win64`

on Appveyor the filenames are too long https://ci.appveyor.com/project/NeroBurner/hunter/build/1.0.3/job/3k13cifuvsqj8hhh#L5785

```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "suitesparseconfig.dir\Release\suitespa.0C0D54C4.tlog\suitesparseconfig.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\projects\hunter\_testing\Hunter\_Base\984c9fc\13789f3\3bc7309\Build\SuiteSparse\Build\SuiteSparse-Release-prefix\src\SuiteSparse-Release-build\SuiteSparse\SuiteSparse_config\suitesparseconfig.vcxproj] [C:\projects\hunter\_testing\Hunter\_Base\984c9fc\13789f3\3bc7309\Build\SuiteSparse\Build\SuiteSparse-Release.vcxproj]
```

On linux the builds fail because pip3 is not found
https://travis-ci.org/NeroBurner/hunter/jobs/278090299#L419

Have I made a mistake while merging? Or do I need to do some special configuration on appveyor and travis-ci websites?

**Comment by ruslo** [comment]
> Then I merged pkg.template

Currently there is no such step in documentation, I'm doing it myself. Need to think what to do if `pkg.<name>` is not up-to-date.

> on Appveyor the filenames are too long

You can try HUNTER_BINARY_DIR but this feature is not well designed:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed

> On linux the builds fail because pip3 is not found

I guess it's an old `.travis.yml`, I've pushed updates to `pkg.suitesparse`.

**Comment by NeroBurner** [comment]
Linux Builds are still failing with same error after rebase
- https://github.com/NeroBurner/hunter/commits/test.suitesparse
- https://travis-ci.org/NeroBurner/hunter/builds/278105056?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
I've pushed fix:
* https://github.com/ingenue/hunter/commit/9c71c0bc3ec99bedf4757f6630109b39eb084c52

Should be good now:
* https://travis-ci.org/ingenue/hunter/builds/278106205

**Comment by NeroBurner** [comment]
yes, looks very good :+1: 

- https://ci.appveyor.com/project/NeroBurner/hunter/build/1.0.7
- https://travis-ci.org/NeroBurner/hunter/builds/278112983?utm_source=github_status&utm_medium=notification
