### ISSUE TITLE
Android NDK: GCC doesn't like '-mthreads' when building boost library

### ISSUE THREAD

**Issue by rcdailey** [ruslo/hunter#516]
I am using `hunter_add_package()` for boost 1.59.0. I tested this first on Windows against MSVC and it works great. Boost builds fine.

Now I'm building using the Android NDK, specifically the ARM architecture using GCC 4.9 + GNU STL (static)

First issue I ran into was the API level. We use Android SDK 15, and subsequently use the same version on the NDK as well. This wasn't supported out of the box by Hunter (minimum was 16) so I made the following change to `default.cmake`:

```
  elseif(_is_api_15)
    hunter_config(Android-Google-APIs VERSION 15_r04)
    hunter_config(Android-Intel-x86-Atom-System-Image VERSION 15)
    hunter_config(Android-SDK-Platform VERSION 15_r05)
    hunter_config(Sources-for-Android-SDK VERSION 15)
```

This seemed to work fine and I got past that issue. Now when building boost I get a compiler failure because `-mthreads` is being passed to GCC which it doesn't accept:

```
gcc.compile.c++ bin.v2\libs\system\build\gcc-ndk\debug\link-static\threading-multi\error_code.o
arm-linux-androideabi-g++.exe: error: unrecognized command line option '-mthreads'

    "E:/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++.exe" "-fexceptions" "-frtti" "-fpic" "-Wno-psabi" "--sysroot=E:/android/ndk/platforms/android-8/arch-arm" "-funwind-tables" "-finline-limit=64" "-fsigned-char" "-no-canonical-prefixes" "-march=armv7-a" "-mfloat-abi=softfp" "-mfpu=vfpv3-d16" "-fdata-sections" "-ffunction-sections" "-Wa,--noexecstack" "-DANDROID" "-isystem" "E:/android/ndk/platforms/android-8/arch-arm/usr/include" "-isystem" "E:/android/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include" "-isystem" "E:/android/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include" "-isystem" "E:/android/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward"  -ftemplate-depth-128 -O0 -fno-inline -Wall -pedantic -g -mthreads  -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_STATIC_LINK=1  -I"." -c -o "bin.v2\libs\system\build\gcc-ndk\debug\link-static\threading-multi\error_code.o" "libs\system\src\error_code.cpp"
```

I googled this and found [this SO question](http://stackoverflow.com/questions/8274430/unrecognized-command-line-option-while-compiling-boost-for-android-on-cygwin) (not exactly the same issue but seems somewhat related; may provide a hint to the root cause) where the user found out the solution was to make a change to `gcc.jam`. Do you have any feedback on how I can solve this problem?
##

**Comment by ruslo** [comment]
> so I made the following change to default.cmake

Feel free to send pull request. Also this can be improved by using this feature https://github.com/ruslo/hunter/issues/55.

> Do you have any feedback on how I can solve this problem?

Need to improve Boost build scheme.

**Comment by rcdailey** [comment]
Can you elaborate on "need to improve boost build scheme"? This is something I'd like to solve. If there is a temp workaround I can use for now please go into detail.

Thanks.

**Comment by rcdailey** [comment]
I'm looking at `url_sha1_boost_library.cmake.in`, and you have this:

```
if("@ANDROID@")
  set(toolset_name "gcc")
  set(toolset_version "ndk")
```

Does this mean you force GCC to be used if android is used to build the library? I'm not quite sure of the purpose of this file, but I'm just poking around trying to find out where you instruct boost to build with the android toolchain, and hopefully somewhere I can hack in a fix to remove the `-mthreads` option.

**Comment by ruslo** [comment]
> I'm looking at url_sha1_boost_library.cmake.in

Yes, this is right file to patch.

> Does this mean you force GCC to be used if android is used to build the library?

I guess this one something that "just work" (tested Android on Linux and OSX: https://travis-ci.org/ingenue/hunter/builds/158362786). If you know how it should be done nicely please share this info. This is mainly about Boost b2 build procedures.

> I'm not quite sure of the purpose of this file

It's a template file, it will be configured to CMakeLists.txt and build.

**Comment by rcdailey** [comment]
Honestly I'm trying to squeeze more details out of you but I'm not doing a good job ;)

I think you assume I know more about building boost & internals of Hunter than I really do. I only started looking at it today for the first time. I really have no idea where to start. I'm happy to contribute, but I'll need your help in getting pointed in the right direction and where to look.

Maybe it will help if I go over exactly how I'm utilizing the Android toolchain my project.

First, I invoke CMake like follows:

```
cmake ".." -G"Ninja" \
    -DCMAKE_BUILD_TYPE="Release" \
    -DCMAKE_TOOLCHAIN_FILE="android.toolchain.cmake" \
    -DANDROID_NATIVE_API_LEVEL=android-15 \
    -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9
```

The `android.toolchain.cmake` file is a conglomeration of [takanome's android toolchain file](https://github.com/taka-no-me/android-cmake) and a mixture of merges from other forks to add continued support for newer NDK versions and other toolchains within the NDK (See my fork [here](https://github.com/rcdailey/android-cmake) which I update with these merges; this is also the exact version of the toolchain file I am using right now).

Internally I think that the toolchain file sets `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` so that CMake is aware of the NDK's specific compiler executable.

It's possible to switch to a different implementation of STL (such as LLVM-STL) and also different compiler (Such as Clang). Your build process for boost should not assume a specific toolchain and instead utilize CMake variables to detect what toolchain is being used and adjust boost options accordingly to function properly in the Android NDK context.

I can help with this but I need pointers on what to change, how to change it, and so on. I'm not only unfamiliar with bjam (I hate it actually, because it's a pain to deal with and understand), but I'm unfamiliar with how you are effectively "patching" the bjam scripts to make boost build the way you expect it to.

Please help me understand this in further detail so I can make this work in a more flexible way for you. Thanks in advance.

**Comment by ruslo** [comment]
> Internally I think that the toolchain file sets CMAKE_C_COMPILER and CMAKE_CXX_COMPILER so that CMake is aware of the NDK's specific compiler executable.

No it is not. You have to use toolchain file to set global variables. I've added section to documentation: https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html

> The android.toolchain.cmake file is a conglomeration of takanome's android toolchain file and a mixture of merges from other forks to add continued support for newer NDK versions and other toolchains within the NDK (See my fork here which I update with these merges

Just for your info Android will be supported from the box with CMake 3.7 release: https://gitlab.kitware.com/cmake/cmake/merge_requests/62. I recommend you to start experimenting with it.

> I'm not only unfamiliar with bjam

Me too. Usually I do surf web for answers and do apply found fixes/workarounds. Also I do report bugs: https://svn.boost.org/trac/boost/ticket/12217. Hunter do no magic and can't fix problems automatically, it's a platform for sharing solutions in organized manner.

> but I'm unfamiliar with how you are effectively "patching" the bjam scripts to make boost build the way you expect it to

Just like I said there is template `url_sha1_boost_library` file that will be used to generate CMakeLists.txt with ExternalProject_Add. All the stuff that you need to do to fix the issue will happens there.

I recommend you to read this wiki page: https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy about testing ([AppVeyor config](https://github.com/ruslo/hunter/blob/master/appveyor.yml)).

**Comment by rcdailey** [comment]
I fixed that particular issue by adding this to the url_sha1 file for boost library:

```
if("@ANDROID@")
  list(APPEND build_opts target-os=android)
endif()
```

I need to read the dev/contrib docs you have to see how I can get the HunterGate download of Hunter to be an actual repo clone, so I can contribute a branch with my changes.

**Comment by ruslo** [comment]
> I need to read the dev/contrib docs you have to see how I can get the HunterGate download of Hunter to be an actual repo clone, so I can contribute a branch with my changes.

See the link above about testing. I recommend you to have two separate HUNTER_ROOT's: one git cloned for testing where you can run `jenkins.py`/push changed, second working HUNTER_ROOT which is managed by HunterGate.

There is no windows testing now so it will happens in next way: you send me a patch with fix, I will run all tests for Boost (without Windows). If patch doesn't broke anything I will merge. Then we will go to adding new Windows test (if you want to have them, though).

**Comment by xsacha** [comment]
@rcdailey Would this help with building Boost for Android on Windows (which currently isn't possible in hunter)?

**Comment by rcdailey** [comment]
I'm actually building Boost for Android on Windows OS. With the changes
provided I can build it just fine. Now I'm moving on to fixing OpenSSL
build problems because it doesn't support running batch scripts when the
target platform isn't windows. This is also because I'm building OpenSSL
for Android on Windows OS. Seems like a lot of Windows support is lacking
in Hunter. I'll be sure to contribute my fixes when I get all libraries I
plan to use working.

**Comment by xsacha** [comment]
@rcdailey Which changes? It still isn't working here.

Is it just from this:
```
if("@ANDROID@")
  list(APPEND build_opts target-os=android)
endif()
```

**Comment by xsacha** [comment]
@rcdailey 
When I add that to the boost library scheme, I still get the same error attempting to compile Android on Windows:

```
'.' is not recognized as an internal or external command,
```

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed
